### ISSUE TITLE
Edits for LM program ending: 1) Remove the liquidity mining bonus column, 2) Repoint stake & delegate to new page

### ISSUE THREAD

**Issue by lufa23** [Sifchain/sifchain-ui#106]
1) Remove the liquidity mining bonus column within our tokens stats in the DEX UI![image_2021-07-01_17-49-53 (1).png](https://images.zenhubusercontent.com/6050a28ecf34f141cf22d02a/dc16efc6-d67a-48cf-b1aa-851c9b0dfe9b), as the program has ended

2) https://dex.sifchain.finance/#/stake-delegate should now just open a new tab: https://wallet.keplr.app/#/sifchain/stake

**Comment by caseyturnerarrington** [comment]
We will do this in the rewrite. Leaving open to keep track of

**Comment by caseyturnerarrington** [comment]
This has been taken care of in the re-write.
