### ISSUE TITLE
Question Mark next to Projected Full amount in the DEX, if clicked it disappears without showing description

### ISSUE THREAD

**Issue by lufa23** [Sifchain/sifchain-ui#123]
![Screenshot 2021-07-27 at 23.41.46.png](https://images.zenhubusercontent.com/6050a28ecf34f141cf22d02a/8f5cb526-37b9-4df2-be9c-609509811bb7)

Probably it will be fixed with the new FE, but just want to make sure we are aware of this

**Comment by caseyturnerarrington** [comment]
This will be handled in revamped DEX. Closing.
