### ISSUE TITLE
Hook up Terra on Cosmos: LUNA/UST

### ISSUE THREAD

**Issue by mccallofthewild** [Sifchain/sifchain-ui#321]
@ajoslin commented on [Thu Oct 07 2021](https://github.com/Sifchain/chainOps/issues/86)

---

@ajoslin commented on [Thu Oct 07 2021](https://github.com/Sifchain/chainOps/issues/86#issuecomment-937964403)

Current status: need a public rpc endpoint for bombay-12

---

@ajoslin commented on [Wed Oct 13 2021](https://github.com/Sifchain/chainOps/issues/86#issuecomment-942470830)

Update: have to use terra station wallet. Integration going well, but Terra Station wallet hasn't implemented IBC transfers yet. Waiting for their new build (estimated end of week).

---

@ajoslin commented on [Wed Oct 13 2021](https://github.com/Sifchain/chainOps/issues/86#issuecomment-942470987)

https://sifchain.slack.com/archives/C01T05LPFEG/p1633978368044300

---

@ajoslin commented on [Fri Oct 15 2021](https://github.com/Sifchain/chainOps/issues/86#issuecomment-944425394)

![image.png](https://images.zenhubusercontent.com/544efd1d7c6ccc6277a597ef/f4675103-1c41-41a6-b33e-a19b1e0c00a8)

Latest date from them is ~1 week, that would be Friday 10/22, for ibc support in terra station. Hopefully sooner... they might have to delay IBC launch too

---

@caseyturnerarrington commented on [Fri Oct 15 2021](https://github.com/Sifchain/chainOps/issues/86#issuecomment-944429349)

@nikohosn FYI^

**Comment by ajoslin** [comment]
We are going to want to do a quick turnaround on Terra. To get it working on FE wallets, we are waiting on whoever finishes Terra IBC Support first: Keplr dev-team or TerraStation dev-team. Once one is supported we want to get it out fast, it'll be a big release for Sifchain

However, we can start testing the Terra testnet relayers with CLI. @Grant Zukel @testing does someone have availability to test this out via CLI? Get testnet Luna+UST here => https://faucet.terra.money/
