### ISSUE TITLE
Sifchain accidentally sent to contract address rather than Metamask

### ISSUE THREAD

**Issue by iss7777** [Sifchain/sifchain-ui#382]
Hi, I was trying to send 24,558 sifchain to my Metamask and instead it went to the contract address.  I don't know how this happened, and it's never happened to me before.  But I would appreciate it if it would be returned to the original address.   

Here's the hash:  https://polygonscan.com/tx/0xf11f537940f64c0a6686756990e294da416c23e38a05191d88caeecec05fa41e.   

Thank you very much for your attention.

**Comment by lufa23** [comment]
hey, i will close this issue and open a new one in another repo for better tracking (gonna keep you updated on this)

**Comment by iss7777** [comment]
Thank you very much.

**Comment by lufa23** [comment]
hey, i have been checking and unfortunately we are not able to retrieve the funds..
The reason for this is that the smart contract is not upgradable, and there is no way for the team to retrieve the amount
