### ISSUE TITLE
Revive playwright e2e tests

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#387]
Get up to date of playwright tests against current UI
and restore existing set of tests (import/export of eth, swaps, add pool/liquidity etc.)

**Comment by pandaring2you** [comment]
Est. 3 more days to get tests working. Need support on localnet

**Comment by pandaring2you** [comment]
From @pgoos 

reviving playwright e2e tests: still about 3 working days from completion. Clarified an issue with non working localnet. Will run tests against testnet BE. That introduces a challenge with consistent wallet funding for each test (where balances are updated by majority of tests). Every test will run on a fresh keplr/metamask account. I added support in playwright for handling new wallets creation.

**Comment by pandaring2you** [comment]
Becomes defunct with sifchain.js
