### ISSUE TITLE
Improve rewards calculator UX

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#409]
Things to improve:

- when Rowan amount or APR is unrealistically high, things might go out of the screen. Same if Rowan price at purchase is very big, then Initial investment value gets crazy (let's manage how we display)
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/43ea0260-5866-4d65-99bd-57f7f0a4d147)

- when APR is not set, then potential return and Rowan rewards estimation are NaN. Same for Rowan price at purchase or Future Rowan price not set (let's rather display 0)
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/c6f605a1-49be-4b88-a254-acd8eaf21d31)

- when APR is crazy huge, then Rowan rewards estimation or potential return might display infinity value
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/8a24a377-b93c-4188-93c0-09ec49b676ce)

**Comment by alanrsoares** [comment]
https://github.com/Sifchain/sifchain-ui/pull/414

**Comment by alanrsoares** [comment]
@pgoos here's the preview build from vercel:
https://sifchain-ui-4kbjtrp56-sifchain.vercel.app/#/calculator
