### ISSUE TITLE
Internal regression testing

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#432]
Test cases to cover: https://docs.google.com/spreadsheets/d/1fjCLO3IclBfN6a236U1vydSp9EyqEQNQ9ms4VuDXO3o/edit#gid=0 
exploratory testing is good enough as well

Areas to cover:
1. Pooling, Liquidity
2. Swap
3. IBC Import/export (w/ mainnet)
4. ERC-20 import/export
5. other pages: Pool Stats, Stake, Documents, More
6. rewards
7. rewards calculator
8. Balances
Environment url: https://devnet.sifchain.finance/?_env=testnet

**Comment by bksifchain** [comment]
2. Swap - Swap functionality is generally working as expected. Found 1 main bug
- Removing slippage causes modal to disappear
  - Open swap page
  - Delete values in slippage
  - Try entering a value in any field
  - The modal disappears

5. other pages - no issues
7. rewards calculator - no issues

**Comment by alanrsoares** [comment]
Did a bunch of testing on swaps, pooling and unpooling. Both on a local build (from develop) pointing to mainnet and on devnet.sifchain.finance also pointing to mainnet. No major issues.

However in one instance, after unpooling Osmo and navigatingt to the Swap page and trying to select Osmo from the token dropdown, I started seeing this error in the console:
![image.png](https://images.zenhubusercontent.com/61dcd57fecd50291ad1d9155/4a05425c-0be3-4093-9491-8808fa292d25)

**Comment by pgoos** [comment]
All issues got fixed and re-tested. Devnet passed to Applause for their test cycle.
