### ISSUE TITLE
Unable to add liquidity asymmetrically without non-rowan asset

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#503]
the issue with pooling exists when adding ROWAN asymmetrically **without** another asset in the pool.

- ie, add 10 ROWAN, 0 LUNA

Keplr notification is not shown. It fails earlier with the following error in the console
```
Uncaught (in promise) Error: Attempt to retrieve the asset with key "uluna" before it had been cached.
```
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/ad937f76-3a02-4b52-9d4f-4f4f8220360f)

Video:
https://vimeo.com/manage/videos/694165897

**Comment by tien** [comment]
From looking briefly at how the assets are being loaded, this seems like an issue with tokenregistry on mainnet?

@alanrsoares can you confirm?

**Comment by tien** [comment]
@pgoos might have also been fixed in #506 can you help check?

**Comment by tien** [comment]
@pgoos can you help narrow down the affected paths? I tried doing this for several pools in testnet and haven't got any issues so far,

**Comment by pgoos** [comment]
@tien try on Devnet instead. I have just reproduced the issue there
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/08509629-0fe4-4b77-bd5e-41fdf02483fd)

**Comment by pgoos** [comment]
It doesn't matter which BE you use. I tried with both testnet and mainnet BE.
