### ISSUE TITLE
Put up a warning that adding or removing via ledger is currently disabled

### ISSUE THREAD

**Issue by jkbrooks** [Sifchain/sifchain-ui#595]
### Is your proposal related to a problem?

I am currently frustrated when I go to the dex and try to add or remove liquidity with my ledger and get halfway through but ultimately get an error.

### Describe the solution you'd like

Please put up a warning in a better on the website until this issue has been fixed

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by bksifchain** [comment]
this is done
