### ISSUE TITLE
Add/Unbond liquidity not working for ledger devices

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#597]

**Comment by pgoos** [comment]
Jon Hancock  11 hours ago
@Piotr Gesicki this Monday we should have an answer on the Ledger problem.  If it's a sifnode problem, it will take at least a week to get a fix out.  If it's just a front end issue, perhaps sooner.  Friday's perspective was it is a sifnode problem.  I would not classify this as no progress.

**Comment by pgoos** [comment]
Jon Hancock  11 hours ago
@sif_moon @briankobler (ET) Hope to get a better answer on how this happened after Austin, et al have looked into it.
:pray:
1

white_check_mark
+1
raised_hands




Austin  11 hours ago
I believe @Tim Lind put a fix branch together based on some community findings but I think we still need to test
:+1:
2
:pray:
1


Jon Hancock  11 hours ago
thanks.  @Tim Lind I'd like you to explain to us what the problem is.  How it stopped working.  If you have a PR ready, can you please share the link.  If this is all in zenhub, please just share that link. (edited)

**Comment by sheokapr** [comment]
@timlind - I tested with a Ledger device today, Add-Liquidity went through fine, Unbond-Liquidity txn failed with a broadcast txn panic error (error seen in Console) which seems to be a sifnode error:

![image.png](https://images.zenhubusercontent.com/608fcda801e9634c34aa4c64/e5e97119-7873-45e3-ad52-93a77610590f)

**Comment by timlind** [comment]
We haven't updated devnet with a fix yet.

**Comment by sheokapr** [comment]
Ok, sure, please let me know when it is pushed to DevNet/TestNet, I have a ledger device now to perform this testing and validate the fixes.

**Comment by bksifchain** [comment]
Unbonding and remove is working. Add is still pending.
