### ISSUE TITLE
ERC-20 imports from Ethereum not working

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#601]
Ethereum imports from metamask are throwing an error “cannot read properties of undefined reading call”
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/d02ae8dc-3afe-4453-a6db-11aced390cdf)

**Comment by alanrsoares** [comment]
fixed by #606

**Comment by alanrsoares** [comment]
fixed by https://github.com/Sifchain/sifchain-ui/pull/606
