### ISSUE TITLE
Non-Eth ERC-20 tokens balances are not fetched into DEX

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#602]
Only ETH balances are shown
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/0de70461-a5a2-4f66-b344-5d67a5d68749)
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/c51f589a-c875-44e7-946e-5379a36bff8e)

**Comment by alanrsoares** [comment]
fixed by #606
