### ISSUE TITLE
Enhancement Request: Add pool weights to add liquidity section

### ISSUE THREAD

**Issue by abratusz** [Sifchain/sifchain-ui#609]
It has been requested to enable people to see the pool weights when add liquidity.

In the pop-up, after people click add liquidity,  display the current pool ratio is so that people know what they are adding.

**Comment by alanrsoares** [comment]
the `$TOKEN per ROWAN`and `ROWAN per $TOKEN` values on the add liquidity modal are already the pool ratios

**Comment by abratusz** [comment]
But users are often confused at what ratio they are adding. For example, when adding ROWAN:AtOM it may say

139 ROWAN: 1 ATOM, but what is the pool ratio or w_xt , w_yt of PMTP at that time (https://docs.google.com/spreadsheets/d/1Ty4TrZivw86LEgvj8_Deg-PG3rvhU-t9rRnWbuqUPxs/edit#gid=1397045407)

**Comment by bksifchain** [comment]
Display the ratio of the pool in the add liquidity modal
Ex: 
Pool ratio
ROWAN:ATOM  232:1
