### ISSUE TITLE
UI Change Request: Change "Pool at Equal Ratios" to "Pool at Pool Ratio"

### ISSUE THREAD

**Issue by abratusz** [Sifchain/sifchain-ui#621]
Many users are confused by the "Pool Equally" ratio because the outcome is not pooling at equal ratios. As such, it would avoid a lot of confusion if we changed the copy to "Pool at Pool Ratio".

Would be awesome if we have a tooltip as well that says something like: 'As an effect of PMTP, the ratio of assets in a pool is constantly shifting. New liquidity additions to the pool are calculated at the current pool ratios by the UI. When you add liquidity, you will be asked to provide the amount of tokens that match the current ratio of the pool - currently xx:xx. See additional details [here](https://docs.sifchain.finance/using-the-website/web-ui-step-by-step/pool).' (where xx:xx is the current ratio).

**Comment by sifmoon** [comment]
@bksifchain any chance we can expedite this? This is causing a lot of questions in discord right now :(.

**Comment by bksifchain** [comment]
@abratusz @sifmoon - isnt that request the wrong statement though?

We are pooling equally based on pool ratios (not PMTP prices). And the UI says "Pool at Equal Ratios". Do you want to change this to "Pool at pool ratio"?

**Comment by abratusz** [comment]
Yes – that's perfect @bksifchain – thanks!
