### ISSUE TITLE
create env where FE points to tempnet with lockPeriod=0

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#685]
This is to verify an impact of setting unbonding request period (lockPeriod) to 0 on the rest of the flow through FE.
It should be done with tempnet because of missing admin accounts for devnet/testnet with roles PMTPREWARDS.
* deploy tempnet that allows hooking existing test admin accounts for setting rewards/lock parameters
* modify sifchain-ui devnet config to point to tempnet rpc/api
* add the tempnet rpc/api info into proxies

If needed, account funding and pool creation should also be done.

**Comment by pandaring2you** [comment]
Setting lock period to 0 is part of 0.13.4 . Aiming to get this done by EOD

**Comment by bksifchain** [comment]
closing as this is now released
