### ISSUE TITLE
Create new playwright framework for FE v3

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#688]
Create a framework where playwright and playwright test runner are utilised.
The scope is:
* create a github workflow
* install all extensions (keplr, metamask, wallet connect) and load them inside chrome persistent context

Test scripts will have separate follow-up tasks

**Comment by pandaring2you** [comment]
Est 2 days for initial PR. Est 3 weeks for initial release of FE v3. Brian will be timing this task/testing with that release.

**Comment by pandaring2you** [comment]
Est PR tomorrow

**Comment by pandaring2you** [comment]
Branch ready. Can't fully test changes remotely - missing access rights to the Vercel repo. @khdegraaf  sync w/Piotr to give permissions.

**Comment by pgoos** [comment]
PR: https://github.com/Sifchain/sifchain-ui-next/pull/30

**Comment by pandaring2you** [comment]
@pgoos to create followup tasks to extend framework
