### ISSUE TITLE
Wallet integrations

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#696]
Playwright chrome extensions wallet integrations for FE v3:
* MM
* Keplr
* Coinbase wallet
* WalletConnect

**Comment by pandaring2you** [comment]
ETA tomorrow

**Comment by pandaring2you** [comment]
ETA EOW

**Comment by pgoos** [comment]
Wallet integration is ready but with latest Keplr extension version, importing existing seed phrase UI changed which requires additional changes in playwright e2e.

**Comment by pandaring2you** [comment]
ETA tomorrow

**Comment by pandaring2you** [comment]
Integrations are now functional. Will push changes tonight
