### ISSUE TITLE
Hide Liquidity Pools with less than 10k TVL behind a toggle

### ISSUE THREAD

**Issue by abratusz** [Sifchain/sifchain-ui#701]
### Requirements
- Add a toggle control to the top right header area of the pools page
  - "Show pools less than $10,000"
  - Default position is off
  - If the user toggles it on, we display pools that contain less than $10K in TVL

Ask: 

Hide all liquidity pools with less than $10,000 TVL behind a toggle on the front-end. Optimally, when toggled on, this will not display the ability to swap against those pools, or display the pools on any page on the FE of the DEX. 

Context: 
https://www.notion.so/sifchain/Hidden-Pools-e87b54ee767c43d1b26dde8e0be1a4c2

**Comment by abratusz** [comment]
Is it possible to also include the pool stats page in this in order to have consistency across the FE?

**Comment by alanrsoares** [comment]
absolutely @abratusz, can add that to the backlog

**Comment by abratusz** [comment]
thanks Alan
