### ISSUE TITLE
Users cannot import Cosmos tokens from Ethereum via Peggy

### ISSUE THREAD

**Issue by jkbrooks** [Sifchain/sifchain-ui#708]
**Current behavior**
Users cannot select Cosmos tokens (such as REGEN or XPRT) from the Sifchain UI to import them from Ethereum 

**Expected behavior**
Users should be able to select these tokens in the UI for import

**Steps to reproduce**
- Hold a Cosmos token such as REGEN or XPRT in an Ethereum wallet 
- Visit the page for importing tokens to Sifchain (see image attached)
- the Cosmos tokens will not appear as an option to import

**What tokens are you interacting with when this issue occurs?**
Please list the "From" and "To" tokens (eg. From: cETH, To: Rowan

REGEN, XPRT (May be more)

Note, these are versions held on Ethereum and have been previously exported from Sifchain!

**Screenshots**

[image](https://user-images.githubusercontent.com/129074/182006804-d09e1df9-2016-4d2a-ba3d-1466f43a3fba.png)

**Ethereum (If applicable) : Please provide relevant info**
Eg. Your Ethereum address, tx hash (EtherScan link)

https://etherscan.io/address/0x07b63b5e9CF66cD1252322FF2Bc83Fc70aF0599b

**Comment by emperorjm** [comment]
Document on how to import ERC20 via Peggy bridge using the Etherscan interface https://docs.google.com/document/d/161bXWtViU7R2K1UnicHVFnXhcNi00jT2pbFekruwMMM/edit#

**Comment by pandaring2you** [comment]
Token recovery tool pipeline is broken - need @gzukel to look into fixing issue. Token recovery tool should allow the user to import/export without UI once this is fixed. Jordan to look into testing a cosmos token (will import all of the token).

**Comment by Brando753** [comment]
The token recovery tool https://token-recovery.sifchain.finance/ has been since updated and to my knowledge works fine, unassigning myself unless there are new issues.

**Comment by pandaring2you** [comment]
hey @lufa23 - please close if this has been resolved
