### ISSUE TITLE
UI and E2E testing of new flat swap fee rate

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#732]
Scope:
* FE V2 - feature, e2e and regression testing
* FE V3 - feature, e2e testing

**Comment by pandaring2you** [comment]
Estimating to have test plan by EOD and start work tomorrow.

**Comment by pgoos** [comment]
@alanrsoares @ghuznee when swap fee rate is very high - almost at max allowed value `0.99` or `1`, then UI serves conflicting messages `Price Impact Too High` and in `Price Impact` value we can see that it's very low.
In this specific (edge) case, min. received is < 0  (because of swap fee is taking everything or almost everything). Maybe we should enhance `Price Impact Too High` message.
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/887b7783-8a13-4e50-9fe4-27fd83d78f50)

**Comment by pgoos** [comment]
In case of negative pmtp rate, swap fee is less than according to equation. Also as a result, swap amount is less than expected (the slippage was minimal)
pmtp rate applied `-0.000321000000000000`, according to equation, swap fee should be `5.4469`, when calculated by the FE was `~5.29`, expected swap amount (y) around `1810` when actually was `1756` (less by about 3%).
![image.png](https://images.zenhubusercontent.com/609164048a6d7799b05f3c9b/396bdf94-c7ba-4c4d-a583-3db50dc185d5)
@joneskm @alanrsoares what do you think?
