### ISSUE TITLE
position $ value is NaN when leverage is changed

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#744]
Steps to reproduce:
1. Go to https://devnet.sifchain.finance/?_env=testnet
2. Click on Margin
3. Set collateral value to 100
4. Change leverage from 10 to 5

**Expected behavior**
Position values are updated correctly

**Actual behavior**
$ value of the position is NaN

https://images.zenhubusercontent.com/371524097/f2c69297-9c43-4ea8-9547-1dba74960cab/screen_recording_2022_09_06_at_17_06_31.mov

**Comment by oieduardorabelo** [comment]
Update available in https://sifchain-margin.vercel.app/margin

@pgoos you can check this again
