### ISSUE TITLE
when position value is manually set, collateral value is messed up

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#745]
Steps to reproduce:
1. Go to https://devnet.sifchain.finance/?_env=testnet
2. Click on Margin
3. Set collateral to 100
Notice position value is 885 rowan
4. Set position to 885 manually

**Expected behavior**
Collateral value calculated is ~100

**Actual behavior**
Collateral value calculated is ~9932

**Comment by oieduardorabelo** [comment]
cc @alanrsoares

**Comment by oieduardorabelo** [comment]
this is ready to test at https://sifchain-margin.vercel.app/

cc @pgoos
