### ISSUE TITLE
docker build fails with /ui/Dockerfile

### ISSUE THREAD

**Issue by patrickdaj** [Sifchain/sifchain-ui#79]
**Current behavior**
Trying to build docker image for running locally.

**Expected behavior**
Docker build command to complete without errors.

**Steps to reproduce**
git clone https://github.com/Sifchain/sifchain-ui/ && cd sifchain-ui/ui
docker build -t whatever/sifchainui:testing -f Dockerfile .

Identify exact point in reproduction steps where expectation is violated
Step 17 of docker build.

Example of identifying point where expectation is violated:

Step 17/23 : RUN yarn core:build
 ---> Running in 834291c8a16c
yarn run v1.22.5
error Command "core:build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn core:build' returned a non-zero code: 1

**What tokens are you interacting with when this issue occurs?**
Please list the "From" and "To" tokens (eg. From: cETH, To: Rowan
N/A

**Screenshots**
N/A

**Ethereum (If applicable) : Please provide relevant info**
Eg. Your Ethereum address, tx hash (EtherScan link)
N/A

**Sifchain (If applicable) : Please provide relevant info**
Eg. Your Sifchain address, link to tx on block explorer
N/A

**Additional context**
N/A

**Other Helpful Bug Filing Info**
N/A

Don't duplicate (make sure issue hasn't already been filed)
Done

Don't mention multiple problems in one issue (just create a new issue if you observe multiple issues)
Done

Make the issue objective, don't speculate or add opinion that isn't verifiable
Done

Add a clear title that includes a relevant area of the code (for example: [Peggy] or [Chainops])
Done

Format issue in markdown
Done

Where possible, include links to relevant code on Github for easy search or copy code snippets
Done

Where possible, include code snippets from the command line to easily search
Done

**Comment by patrickdaj** [comment]
When I do a "git checkout master" before bulding I get the following error instead.

`
Step 17/23 : RUN yarn core:build
 ---> Running in 3a5ffc720f5a
yarn run v1.22.5
$ cd core && yarn build
warning package.json: License should be a valid SPDX license expression
$ tsc --noEmit && tsc -p ./tsconfig.compile.json
src/entities/formulae.calculateExternalExternalSwapResult.test.ts(3,19): error TS2307: Cannot find module '../../../../test/test-tables/doubleswap_result.json' or its corresponding type declarations.
src/entities/formulae.calculateLiquidityProviderFee.test.ts(2,19): error TS2307: Cannot find module '../../../../test/test-tables/singleswap_liquidityfees.json' or its corresponding type declarations.
src/entities/formulae.calculateLiquidityProviderUnits.test.ts(3,20): error TS2307: Cannot find module '../../../../test/test-tables/pool_units_after_upgrade.json' or its corresponding type declarations.
src/entities/formulae.calculateLiquidityProviderUnits.test.ts(26,41): error TS7031: Binding element 'r' implicitly has an 'any' type.
src/entities/formulae.calculateLiquidityProviderUnits.test.ts(26,44): error TS7031: Binding element 'a' implicitly has an 'any' type.
src/entities/formulae.calculateLiquidityProviderUnits.test.ts(26,47): error TS7031: Binding element 'R' implicitly has an 'any' type.
src/entities/formulae.calculateLiquidityProviderUnits.test.ts(26,50): error TS7031: Binding element 'A' implicitly has an 'any' type.
src/entities/formulae.calculateLiquidityProviderUnits.test.ts(26,53): error TS7031: Binding element 'P' implicitly has an 'any' type.
src/entities/formulae.calculateLiquidityProviderUnits.test.ts(26,56): error TS7031: Binding element 'expected' implicitly has an 'any' type.
src/entities/formulae.calculateLiquidityProviderUnits.test.ts(26,68): error TS7006: Parameter 'index' implicitly has an 'any' type.
src/entities/formulae.calculatePriceImpact.test.ts(2,40): error TS2307: Cannot find module '../../../../test/test-tables/singleswap_standardslip.json' or its corresponding type declarations.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn core:build' returned a non-zero code: 1
`

**Comment by ryardley** [comment]
The Dockerfile in master has been deprecated and removed. Deployed code is built via the new `yarn build` scripts in `develop`
